### ISSUE TITLE
Switch manual tracing examples to use beelines trace schema

### ISSUE THREAD

**Issue by christineyen** [honeycombio/examples#11]
Per https://github.com/honeycombio/opencensus-exporter/pull/5/files

Also update docs at https://docs.honeycomb.io/working-with-data/tracing/send-trace-data/#manual-tracing

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
